#pragma once
#include <SFML\Graphics.hpp>
sf::String TileMap[2][30] = {
   {
	   "gggggggggggggggggggggggggggggg",
	   "ggggggggggwwgggggggggggggggggg",
	   "gggggggggwwwwggggggggggggggggg",
	   "ggggggggwwwwwwgggggggggggggggg",
	   "ggggggggwwwwwwgggggggggggggggg",
	   "gggggggggwwwwggggggggggggggggg",
	   "ggggggggggwwgggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg",
	   "gggggggggggggggggggggggggggggg"
   },
   {
	   "                              ",
	   "    tC   y       b            ",
	   "    CC                 b      ",
	   "    b b         tCtC          ",
	   "      y         CCCC   tC     ",
	   "    b          b       CC     ",
	   "     b                  b     ",
	   "           y   y   b          ",
	   "         b                    ",
	   "   b            tC     b      ",
	   "        b       CC b          ",
	   "     tC      tC               ",
	   "     CC      CC       tC      ",
	   "    b  y     b  y     CC      ",
	   "                    tC    y   ",
	   "     tC    b        CC b      ",
	   "     CC            y     b    ",
	   "    b        tC               ",
	   "       b     CC b     b       ",
	   "    y                         ",
	   "           b         b        ",
	   "    tC                        ",
	   "    CC         tC       tC    ",
	   "  b     y      CC   b   CC    ",
	   "    tC                        ",
	   "    CC        b               ",
	   "   b     b               tC   ",
	   "   b               tC    CC   ",
	   "             y     CC   b     ",
	   "                              "
   }
};